<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Models\CommandRun;
use App\Models\Customer;
use App\Models\Manuscript;
use App\Models\Tenant;
use Illuminate\Console\Command;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * One-off: correct the metadata on the imported "2026-08" baseline so its
 * dates reflect reality.
 *
 * The `2026-08` manuscript is v1's register, generated by v1's real
 * `manuscript:calculate` run on **2026-07-22 12:04:11** (dump generation
 * time; v1 `command_runs` id 14). `ManuscriptImportAugust` loaded it on
 * 2026-08-28, so every "Run at" surface currently shows the import date,
 * not the true run date. In this system a run executed near the end of
 * month M-1 governs month M (business-rules.md #2) — so the August
 * manuscript correctly "ran at" late July, and the upcoming September run
 * will correctly "ran at" late August.
 *
 * Fixes, on tenant swecom:
 *   1. The synthetic `command_runs` row for `manuscript:calculate` / period
 *      `2026-08` (the ManuscriptRerunGuard sentinel): `ran_at` and
 *      `published_at` -> 2026-07-22 12:04:11.
 *   2. `manuscripts` rows for period `2026-08`: `created_at` -> the same
 *      timestamp; `updated_at` -> the same ONLY where it still equals
 *      `created_at` (untouched rows) — rows edited since the import keep
 *      their real edit time.
 *   3. Phantom `prepaid_months_remaining` / `prepaid_rate` left on the
 *      `2026-08` rows for customers 24 (MA TE) and 39 (FON CHRISTINA) by
 *      the buggy `manuscript:recalculate-one` incident -> zeroed (their
 *      money columns were already re-corrected; pmr/prate were missed).
 *
 * No manuscript figure other than pmr/prate on those two rows changes.
 * Dry run by default; `--apply` to write. Idempotent, tenant-guarded.
 * Safe to delete once run.
 */
class ManuscriptCorrectAugustBaseline extends Command
{
    protected $signature = 'manuscript:correct-august-baseline
        {--tenant=swecom : Tenant slug/id}
        {--apply : Write the changes (default is a dry run)}
        {--force : Allow running against a tenant other than the default}';

    protected $description = 'Set the imported 2026-08 baseline run date to v1\'s real run (2026-07-22) and clear two phantom prepaid counters';

    private const PERIOD = '2026-08';

    private const TRUE_RAN_AT = '2026-07-22 12:04:11';

    /** customer_id => name fragment, for the phantom pmr/prate clear. */
    private const PHANTOM_PREPAID = [24 => 'MA TE', 39 => 'FON CHRISTINA'];

    public function handle(): int
    {
        $tenantId = (string) $this->option('tenant');
        $apply = (bool) $this->option('apply');

        if ($tenantId !== 'swecom' && ! $this->option('force')) {
            $this->error("swecom-specific correction. Refusing tenant \"{$tenantId}\" without --force.");

            return self::FAILURE;
        }

        $tenant = Tenant::find($tenantId);
        if (! $tenant) {
            $this->error("Tenant \"{$tenantId}\" not found.");

            return self::FAILURE;
        }

        $trueRanAt = Carbon::createFromFormat('Y-m-d H:i:s', self::TRUE_RAN_AT);

        tenancy()->initialize($tenant);

        try {
            $run = CommandRun::query()
                ->where('command', 'manuscript:calculate')
                ->where('period', self::PERIOD)
                ->first();

            $rows = Manuscript::query()->where('period', self::PERIOD);
            $rowCount = (clone $rows)->count();
            $untouched = (clone $rows)->whereColumn('created_at', 'updated_at')->count();

            $this->newLine();
            $this->line("<info>2026-08 baseline date correction</info>  tenant={$tenantId}");
            $this->line($apply ? '<comment>MODE: APPLY</comment>' : 'MODE: dry run (pass --apply to write)');
            $this->newLine();

            $this->line('command_runs sentinel: '.($run
                ? "#{$run->id}  ran_at {$run->ran_at}  ->  ".self::TRUE_RAN_AT
                : '<comment>none found — will be skipped</comment>'));
            $this->line("manuscripts (period {$this->quote(self::PERIOD)}): {$rowCount} rows");
            $this->line('  created_at -> '.self::TRUE_RAN_AT." on all {$rowCount}");
            $this->line('  updated_at -> '.self::TRUE_RAN_AT." on the {$untouched} untouched rows (".($rowCount - $untouched).' edited rows keep their real time)');
            $this->newLine();

            $this->line('Phantom prepaid counters to clear:');
            $phantomPlan = [];
            foreach (self::PHANTOM_PREPAID as $cid => $name) {
                $m = Manuscript::query()->where('customer_id', $cid)->where('period', self::PERIOD)->first();
                $customer = Customer::query()->find($cid);
                if (! $m || ! $customer) {
                    $this->line("  #{$cid} {$name}: no {$this->quote(self::PERIOD)} row — skipped");

                    continue;
                }
                if (mb_stripos($customer->name, $name) === false) {
                    $this->error("  #{$cid} is \"{$customer->name}\", expected \"{$name}\" — aborting, no changes made.");

                    return self::FAILURE;
                }
                $has = (int) $m->prepaid_months_remaining > 0 || $m->prepaid_rate !== null;
                $this->line("  #{$cid} {$name}: pmr={$m->prepaid_months_remaining} rate=".($m->prepaid_rate ?? 'null').($has ? '  -> 0 / null' : '  (already clear)'));
                if ($has) {
                    $phantomPlan[] = $m;
                }
            }

            $this->newLine();

            if (! $apply) {
                $this->info('Dry run complete. Re-run with --apply to write.');

                return self::SUCCESS;
            }

            DB::transaction(function () use ($run, $trueRanAt, $phantomPlan): void {
                if ($run !== null) {
                    $run->forceFill(['ran_at' => $trueRanAt, 'published_at' => $trueRanAt])->saveQuietly();
                }

                // Query-builder update: a pure timestamp correction on ~446
                // rows should not spray the audit log with 446 rows.
                DB::table('manuscripts')->where('period', self::PERIOD)
                    ->whereColumn('created_at', 'updated_at')
                    ->update(['created_at' => $trueRanAt, 'updated_at' => $trueRanAt]);
                DB::table('manuscripts')->where('period', self::PERIOD)
                    ->whereColumn('created_at', '!=', 'updated_at')
                    ->update(['created_at' => $trueRanAt]);

                // pmr/prate IS a real figure change — through the model so
                // Auditable records it.
                foreach ($phantomPlan as $m) {
                    $m->update(['prepaid_months_remaining' => 0, 'prepaid_rate' => null]);
                }
            });

            $this->info('Applied. Baseline "Run at" is now 2026-07-22; '.count($phantomPlan).' phantom prepaid counter(s) cleared.');

            return self::SUCCESS;
        } finally {
            tenancy()->end();
        }
    }

    private function quote(string $v): string
    {
        return "'{$v}'";
    }
}
