<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Models\Company;
use App\Models\Customer;
use App\Services\ManuscriptService;
use Barryvdh\DomPDF\Facade\Pdf;
use Database\Factories\CompanyFactory;
use Database\Factories\CustomerFactory;
use Database\Factories\ManuscriptFactory;
use Database\Factories\ZoneFactory;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Storage;
use Tests\Feature\Api\Concerns\InteractsWithTenantRoles;
use Tests\TestCase;

/**
 * Exercises the bulk N-up bill grid mechanism (resources/views/pdf/bills/
 * _grid.blade.php + App\Services\ManuscriptService::billDataForCustomers())
 * directly — there is no HTTP route wired to it yet (bulk-select on
 * Manuscripts/Index.tsx is a deliberately deferred follow-up this cycle;
 * this pass only builds the templates/grid MECHANISM). Proves real,
 * multi-customer dompdf renders succeed at density 1/2/4 by asserting the
 * generated bytes are a genuine PDF (the "%PDF-" magic header), not just
 * that no exception was thrown.
 */
class BillGridRenderTest extends TestCase
{
    use DatabaseTransactions;
    use InteractsWithTenantRoles;

    protected function setUp(): void
    {
        parent::setUp();

        $this->initializeTenant();
    }

    /**
     * @return Collection<int, Customer>
     */
    private function customersWithManuscripts(int $count): Collection
    {
        $zone = ZoneFactory::new()->create();
        $period = now()->format('Y-m');

        return collect(range(1, $count))->map(function () use ($zone, $period) {
            $customer = CustomerFactory::new()->create(['zone_id' => $zone->id, 'bill' => 2500]);

            ManuscriptFactory::new()
                ->forPeriod($period)
                ->create(['customer_id' => $customer->id, 'bill' => 2500, 'total_bill' => 2500]);

            return $customer;
        });
    }

    private function assertGridRendersRealPdf(int $density, int $customerCount): void
    {
        CompanyFactory::new()->create();

        $customers = $this->customersWithManuscripts($customerCount);

        $bills = app(ManuscriptService::class)->billDataForCustomers($customers, null);

        $this->assertCount($customerCount, $bills, 'billDataForCustomers() should return one entry per customer with a manuscript.');

        $pdfBytes = Pdf::loadView('pdf.bills._grid', [
            'bills' => $bills,
            'density' => $density,
            'template' => 'classic',
        ])->output();

        $this->assertNotEmpty($pdfBytes);
        $this->assertStringStartsWith('%PDF-', $pdfBytes, "Grid render at density {$density} did not produce a real PDF.");
    }

    public function test_grid_renders_a_real_multi_customer_pdf_at_density_1(): void
    {
        $this->assertGridRendersRealPdf(density: 1, customerCount: 3);
    }

    public function test_grid_renders_a_real_multi_customer_pdf_at_density_2(): void
    {
        $this->assertGridRendersRealPdf(density: 2, customerCount: 5);
    }

    public function test_grid_renders_a_real_multi_customer_pdf_at_density_4(): void
    {
        $this->assertGridRendersRealPdf(density: 4, customerCount: 7);
    }

    /**
     * A density > 1 grid always uses the 'compact' template per cell
     * regardless of the $template argument passed in (Kumba Compact is the
     * one sized for a shared sheet) — pass 'modern' here and confirm the
     * render still succeeds cleanly rather than overflowing/erroring, which
     * is what would happen if a full-A4 template were force-fit into a
     * quarter-page cell.
     */
    public function test_density_four_forces_the_compact_template_regardless_of_selection(): void
    {
        CompanyFactory::new()->create(['bill_template' => 'modern']);

        $customers = $this->customersWithManuscripts(4);
        $bills = app(ManuscriptService::class)->billDataForCustomers($customers, null);

        $pdfBytes = Pdf::loadView('pdf.bills._grid', [
            'bills' => $bills,
            'density' => 4,
            'template' => 'modern',
        ])->output();

        $this->assertStringStartsWith('%PDF-', $pdfBytes);
    }

    /**
     * Ragged final chunk: 5 customers at density 4 leaves a second sheet
     * with only 1 real bill and 3 padded empty cells — proves the grid
     * doesn't error on a non-rectangular final chunk.
     */
    public function test_grid_pads_a_ragged_final_chunk_without_erroring(): void
    {
        CompanyFactory::new()->create();

        $customers = $this->customersWithManuscripts(5);
        $bills = app(ManuscriptService::class)->billDataForCustomers($customers, null);

        $pdfBytes = Pdf::loadView('pdf.bills._grid', [
            'bills' => $bills,
            'density' => 4,
            'template' => 'classic',
        ])->output();

        $this->assertStringStartsWith('%PDF-', $pdfBytes);
    }

    /**
     * The performance-bug regression: Company::logoDataUri() must be
     * resolved exactly ONCE for the whole batch, not once per customer —
     * see ManuscriptService::billDataForCustomers()'s doc comment. Every
     * bill in the batch must carry the SAME logo_data_uri string instance
     * value (not merely equal — literally the one value computed once).
     */
    public function test_logo_data_uri_is_resolved_once_and_shared_across_every_bill_in_the_batch(): void
    {
        Storage::fake('public');

        $company = CompanyFactory::new()->create();
        $company->addMedia(UploadedFile::fake()->image('logo.png', 200, 200))->toMediaCollection('logo');
        Company::forgetCache();

        $customers = $this->customersWithManuscripts(4);
        $bills = app(ManuscriptService::class)->billDataForCustomers($customers, null);

        $logoValues = array_map(fn (array $bill) => $bill['logo_data_uri'], $bills);

        $this->assertNotNull($logoValues[0]);
        $this->assertCount(1, array_unique($logoValues), 'Every bill in the batch should share the same resolved logo data URI.');
    }
}
