<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Models\Company;
use App\Models\Customer;
use App\Services\ManuscriptService;
use Barryvdh\DomPDF\Facade\Pdf;
use Database\Factories\CompanyFactory;
use Database\Factories\CustomerFactory;
use Database\Factories\ManuscriptFactory;
use Database\Factories\ZoneFactory;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Storage;
use Tests\Feature\Api\Concerns\InteractsWithTenantRoles;
use Tests\TestCase;

/**
 * Exercises the bulk N-up bill grid mechanism (resources/views/pdf/bills/
 * _grid.blade.php + App\Services\ManuscriptService::billDataForCustomers())
 * directly. The HTTP route that drives it in production —
 * GET /manuscripts/bills, ManuscriptController::downloadBills(), the
 * Manuscripts → Export → "Download Bills (by zone)" item — is covered by
 * tests/Feature/Web/ManuscriptTest.php; this file stays at the grid/service
 * layer. Proves real, multi-customer dompdf renders succeed at density
 * 1/2/3/4 by asserting the generated bytes are a genuine PDF (the "%PDF-"
 * magic header), not just that no exception was thrown.
 */
class BillGridRenderTest extends TestCase
{
    use DatabaseTransactions;
    use InteractsWithTenantRoles;

    protected function setUp(): void
    {
        parent::setUp();

        $this->initializeTenant();
    }

    /**
     * @return Collection<int, Customer>
     */
    private function customersWithManuscripts(int $count): Collection
    {
        $zone = ZoneFactory::new()->create();
        $period = now()->format('Y-m');

        return collect(range(1, $count))->map(function () use ($zone, $period) {
            $customer = CustomerFactory::new()->create(['zone_id' => $zone->id, 'bill' => 2500]);

            ManuscriptFactory::new()
                ->forPeriod($period)
                ->create(['customer_id' => $customer->id, 'bill' => 2500, 'total_bill' => 2500]);

            return $customer;
        });
    }

    private function assertGridRendersRealPdf(int $density, int $customerCount): void
    {
        CompanyFactory::new()->create();

        $customers = $this->customersWithManuscripts($customerCount);

        $bills = app(ManuscriptService::class)->billDataForCustomers($customers, null);

        $this->assertCount($customerCount, $bills, 'billDataForCustomers() should return one entry per customer with a manuscript.');

        $perPage = in_array($density, [1, 2, 3, 4], true) ? $density : 1;

        $pdf = Pdf::loadView('pdf.bills._grid', [
            'bills' => $bills,
            'density' => $density,
            'template' => 'classic',
        ]);

        $pdfBytes = $pdf->output();

        $this->assertNotEmpty($pdfBytes);
        $this->assertStringStartsWith('%PDF-', $pdfBytes, "Grid render at density {$density} did not produce a real PDF.");

        // The N-up sheet geometry (resources/views/pdf/bills/_grid.blade.php)
        // must fit exactly one sheet per physical page: a filling set of
        // bills has to produce precisely ceil(N / perPage) pages, with no
        // phantom blank page from a row overflowing the A4 sheet.
        $expectedPages = (int) ceil($customerCount / $perPage);
        $actualPages = $pdf->getDomPDF()->getCanvas()->get_page_count();

        $this->assertSame(
            $expectedPages,
            $actualPages,
            "Grid at density {$density} with {$customerCount} bills should render {$expectedPages} pages (ceil(N/perPage)), got {$actualPages} — a row is likely overflowing the 297mm A4 sheet."
        );
    }

    public function test_grid_renders_a_real_multi_customer_pdf_at_density_1(): void
    {
        $this->assertGridRendersRealPdf(density: 1, customerCount: 3);
    }

    public function test_grid_renders_a_real_multi_customer_pdf_at_density_2(): void
    {
        $this->assertGridRendersRealPdf(density: 2, customerCount: 5);
    }

    public function test_grid_renders_a_real_multi_customer_pdf_at_density_3(): void
    {
        $this->assertGridRendersRealPdf(density: 3, customerCount: 7);
    }

    public function test_grid_renders_a_real_multi_customer_pdf_at_density_4(): void
    {
        $this->assertGridRendersRealPdf(density: 4, customerCount: 7);
    }

    /**
     * Grid geometry for density 3: a single-column, 3-rows-per-sheet stack
     * (the same column layout as 2-up, one card per third of the sheet),
     * with each cell targeting one third of the 297mm A4 portrait height.
     * Asserts the generated markup directly rather than the rendered PDF.
     */
    public function test_density_3_tiles_three_rows_in_one_column_per_sheet(): void
    {
        CompanyFactory::new()->create();

        $customers = $this->customersWithManuscripts(7);
        $bills = app(ManuscriptService::class)->billDataForCustomers($customers, null);

        $html = view('pdf.bills._grid', [
            'bills' => $bills,
            'density' => 3,
            'template' => 'classic',
        ])->render();

        // 7 bills at 3-up => 3 sheets (3 + 3 + 1), so 3 <table class="sheet-grid">.
        $this->assertSame(3, substr_count($html, 'class="sheet-grid"'));
        // Each grid cell carries this exact inline style: a single full-width
        // column (100%), one third of the 297mm A4 portrait height MINUS the
        // ~3.4mm of per-row cell chrome (6px+6px padding + border) that dompdf
        // adds on top of the content-box `height` — 99mm - 3.4mm floored to
        // 95mm. 3 rows x 1 col x 3 sheets => 9 cells (padded cells on the
        // ragged last sheet still emit their <td>). Matching this string also
        // proves the cell is NOT the 144mm 2-up/4-up height.
        $this->assertSame(9, substr_count($html, 'width: 100.0000%; height: 95mm;'));
        $this->assertStringNotContainsString('144mm', $html);
    }

    /**
     * A density > 1 grid always uses the 'compact' template per cell
     * regardless of the $template argument passed in (Kumba Compact is the
     * one sized for a shared sheet) — pass 'modern' here and confirm the
     * render still succeeds cleanly rather than overflowing/erroring, which
     * is what would happen if a full-A4 template were force-fit into a
     * quarter-page cell.
     */
    public function test_density_four_forces_the_compact_template_regardless_of_selection(): void
    {
        CompanyFactory::new()->create(['bill_template' => 'modern']);

        $customers = $this->customersWithManuscripts(4);
        $bills = app(ManuscriptService::class)->billDataForCustomers($customers, null);

        $pdfBytes = Pdf::loadView('pdf.bills._grid', [
            'bills' => $bills,
            'density' => 4,
            'template' => 'modern',
        ])->output();

        $this->assertStringStartsWith('%PDF-', $pdfBytes);
    }

    /**
     * Ragged final chunk: 5 customers at density 4 leaves a second sheet
     * with only 1 real bill and 3 padded empty cells — proves the grid
     * doesn't error on a non-rectangular final chunk.
     */
    public function test_grid_pads_a_ragged_final_chunk_without_erroring(): void
    {
        CompanyFactory::new()->create();

        $customers = $this->customersWithManuscripts(5);
        $bills = app(ManuscriptService::class)->billDataForCustomers($customers, null);

        $pdfBytes = Pdf::loadView('pdf.bills._grid', [
            'bills' => $bills,
            'density' => 4,
            'template' => 'classic',
        ])->output();

        $this->assertStringStartsWith('%PDF-', $pdfBytes);
    }

    /**
     * The performance-bug regression: Company::logoDataUri() must be
     * resolved exactly ONCE for the whole batch, not once per customer —
     * see ManuscriptService::billDataForCustomers()'s doc comment. Every
     * bill in the batch must carry the SAME logo_data_uri string instance
     * value (not merely equal — literally the one value computed once).
     */
    public function test_logo_data_uri_is_resolved_once_and_shared_across_every_bill_in_the_batch(): void
    {
        Storage::fake('public');

        $company = CompanyFactory::new()->create();
        $company->addMedia(UploadedFile::fake()->image('logo.png', 200, 200))->toMediaCollection('logo');
        Company::forgetCache();

        $customers = $this->customersWithManuscripts(4);
        $bills = app(ManuscriptService::class)->billDataForCustomers($customers, null);

        $logoValues = array_map(fn (array $bill) => $bill['logo_data_uri'], $bills);

        $this->assertNotNull($logoValues[0]);
        $this->assertCount(1, array_unique($logoValues), 'Every bill in the batch should share the same resolved logo data URI.');
    }
}
